[build]
  base = "frontend"
  environment = { API_URL = "https://api.staging.remixvr.org/api" }

[context.production]
  environment = { API_URL = "https://api.remixvr.org/api" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200